USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/samsung/skomer/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := unknown
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := skomer

BOARD_KERNEL_CMDLINE := "no_console_suspend=1 console=null"
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048 # output of unpackbootimg

BOARD_BOOTIMAGE_PARTITION_SIZE := 0x1000000  # mmcblk0p20
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x1000000  # mmcblk0p21
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x4B000000 # mmcblk0p22
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x4CBB4000 # mmcblk0p25
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/samsung/skomer/kernel

BOARD_HAS_NO_SELECT_BUTTON := true
