#!/bin/bash

# frameworks_av: Support pre-KitKat audio blobs
#
# Patch Set 2: Combined duplicated method
# Change-Id: I6384c13b0944a25cdf0cb90031b2e3698bc3e78d
# Signed-off-by: Jorge Ruesga <jorge@ruesga.com>
cd frameworks/av
git fetch http://review.cyanogenmod.org/CyanogenMod/android_frameworks_av refs/changes/24/53324/2 && git checkout FETCH_HEAD
cd ../..

# build: Add SKIP_SET_METADATA flag
#
# On some of the older devices the recovery doesn't support
# metadata when setting permissions. This allows to use
# set_perm vs set_metadata.
# Enable this behavior by setting SKIP_SET_METADATA := true
# Change-Id: Ib6cf97b5ca28cee8a87975231f3a61b156e77d29
cd build
git fetch http://review.cyanogenmod.org/CyanogenMod/android_build refs/changes/59/53559/4 && git checkout FETCH_HEAD
cd ..

# linker: Avoid logcat spam with some blobs
#
# Many of pre-kitkat blobs would emit a "text relocations" warning which makes logcat completely unreadable.
# This commit will hide this warning to prevent it.
# Change-Id: I8f32b5bbfea33d732320b3ac29da6b0027fbd521
cd bionic
git fetch http://review.cyanogenmod.org/CyanogenMod/android_bionic refs/changes/90/53390/1 && git checkout FETCH_HEAD
cd ..
